### ISSUE TITLE
Allow several --extra-path

### ISSUE THREAD

**Issue by gsemet** [jorisroovers/gitlint#426] opened 2023-02-03 10:10 UTC
Allow extra-path folders. My use case is basically to provide a docker image with a default set of custom rules, but I would like to allow my users to implement their own custom rules in their projects (so they would provide an additional folder to  `--extra-path` and append the rules to `contrib`.

**Comment by jorisroovers** [comment] 2023-02-03 10:17
Duplicate of #395

**Closed by jorisroovers** 2023-02-03 10:17 UTC
