### ISSUE TITLE
gitlint failed with configured commentchar

### ISSUE THREAD

**Issue by DronMDF** [jorisroovers/gitlint#59] opened 2018-03-07 11:50 UTC
```
$ gitlint
Traceback (most recent call last):
  File "/usr/local/bin/gitlint", line 7, in <module>
    from gitlint.cli import cli
  File "/usr/local/lib/python3.6/dist-packages/gitlint/cli.py", line 27, in <module>
    from gitlint.git import GitContext, GitContextError, git_version
  File "/usr/local/lib/python3.6/dist-packages/gitlint/git.py", line 59, in <module>
    class GitCommitMessage(object):
  File "/usr/local/lib/python3.6/dist-packages/gitlint/git.py", line 66, in GitCommitMessage
    COMMENT_CHAR = git_commentchar()
  File "/usr/local/lib/python3.6/dist-packages/gitlint/git.py", line 54, in git_commentchar
    if commentchar.exit_code == 1:  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'exit_code'
```

**Comment by jorisroovers** [comment] 2018-03-29 13:37
I think this is a duplicate of #48 which got merged but hasn't been released to pypi yet. Can you try installing from master and try again?
```
pip install git+https://github.com/jorisroovers/gitlint.git
```

**Comment by jorisroovers** [comment] 2018-03-30 11:19
Closing this as a duplicate, let me know if you still encounter the issue with latest master. I hope to roll a release over the next few days that will include the fix.

**Closed by jorisroovers** 2018-03-30 11:19 UTC
Labels: duplicate
